name = "ANSEL"
uuid = "b917df1c-af64-11e8-1b17-6bb89287bcb3"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
